# Generated by Django 5.2.3 on 2025-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('urgent', 'Urgent')], default='personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
